import type { NextPage } from 'next'
import Head from 'next/head'
import { Box, Typography } from '@mui/material';
import Link from 'next/link'
import MuiLink from '@mui/material/Link';
import { useRouter } from 'next/router';
import Breadcrumbs from '@mui/material/Breadcrumbs';
import { texti18n } from '../../utils/i18nCommon'
import { styled } from '@mui/material/styles';
import {Main, CenterBox} from '../_app'

const Chess: NextPage = () => {
  const { locale } = useRouter()
  const _lc = locale || 'vn'

  return <div>
    <Head>
      <title>{texti18n[_lc].document}</title>
      <meta name="description" content="Generated by TT" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
      <Main>
        <div>
          <Breadcrumbs aria-label="breadcrumb">
            <Link href='/' passHref><MuiLink underline='hover' style={{ cursor: "pointer" }}>{texti18n[_lc].home}</MuiLink></Link>
            <Link href='/chess' passHref><MuiLink underline='hover' style={{ cursor: "pointer" }}>{texti18n[_lc].chess}</MuiLink></Link>
          </Breadcrumbs>
        </div>
        <CenterBox>
          <Typography variant='h4'>
            {texti18n[_lc].content}
          </Typography>
        </CenterBox>
        <div>
          <Link href='/chess/endgame'><a><MuiLink variant='h5' underline='hover'>{texti18n[_lc].endGame}</MuiLink></a></Link>
        </div>
      </Main>
  </div>
}

export default Chess