import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Button from '@mui/material/Button'
import { styled, useTheme } from '@mui/material/styles';

import estyled from '@emotion/styled'
import Box from '@mui/material/Box';
import { Drawer } from '@mui/material';
import Link from 'next/link'


const MyButton = styled(Button)({
  background: "red"
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Test MUI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div> This is Dashboard</div>
      </main>
    </div>
  )
}

export default Home
