import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import MuiLink from '@mui/material/Link';
import { Box, Typography } from '@mui/material';
import { useRouter } from 'next/router';
import Breadcrumbs from '@mui/material/Breadcrumbs';
import { texti18n } from '../../../utils/i18nCommon';
import {Main, CenterBox} from '../../_app'

const EndGame: NextPage = () => {
  const { locale } = useRouter()
  const _lc = locale || 'vn'
  return <div>
    <Head>
      <title>{texti18n[_lc].document}</title>
      <meta name="description" content="Generated by TT" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Main>
      <Breadcrumbs aria-label="breadcrumb">
        <Link href='/' passHref><MuiLink underline='hover' style={{ cursor: "pointer" }}>{texti18n[_lc].home}</MuiLink></Link>
        <Link href='/chess' passHref><MuiLink underline='hover' style={{ cursor: "pointer" }}>{texti18n[_lc].chess}</MuiLink></Link>
        <Link href='/chess/endgame' passHref><MuiLink underline='hover' style={{ cursor: "pointer" }}>{texti18n[_lc].endGame}</MuiLink></Link>
      </Breadcrumbs>
      <CenterBox>
        <Typography variant='h4'>
          {texti18n[_lc].levels}
        </Typography>
      </CenterBox>
      <div>
        <Link href='/chess/endgame/beginner'>
          <a>
            <MuiLink variant='h5' underline='hover'>
              {texti18n[_lc].beginner}
            </MuiLink>
          </a>
        </Link>
      </div>
      <div style={{ marginTop: 10 }}>
        <Link href='/chess/endgame/'>
          <a>
            <MuiLink variant='h5' underline='hover'>
              {texti18n[_lc].classE}
            </MuiLink>
          </a>
        </Link>
      </div>
      <div style={{ marginTop: 10 }}>
        <Link href='/chess/endgame/'>
          <a>
            <MuiLink variant='h5' underline='hover'>
              {texti18n[_lc].classD}
            </MuiLink>
          </a>
        </Link>
      </div>
    </Main>
    </div>
}

export default EndGame
